server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zlbbs?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    database: MySQL
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        default_batch_fetch_size: 20
  thymeleaf:
    cache: false
  mail:
    username: 409322382@qq.com
    password: zxndbuhorfpcbiia
    host: smtp.qq.com

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 50MB

password:
  key: abcdefghijklmnopqrstuvwxyz0123456789

qiniu:
  url: http://r4yotdqih.hd-bkt.clouddn.com/



